services:
  db:
    image: postgres:14.23-alpine3.23
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data:rw

volumes:
  pg_volume:
