services:
  db:
    image: postgres:14.23-alpine3.23
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: dev
    ports:
      - "5432:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data:rw
  app:
    build: .
    container_name: doc-project
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # override since host is now the db service; not localhost
      DATABASE_URL: postgres://postgres:toor@db:5432/dev
    ports:
      - "3000:3000"

volumes:
  pg_volume:
